### ISSUE TITLE
[QUESTION] Use enableGuestAccess with keycloak?

### ISSUE THREAD

**Issue by ouafnico** [Lissy93/dashy#1032]
### Question

Hello

Thanks for dashy !

I'm testing it with keycloak (2.1.0/2.1.1), can we use a `enableGuestAccess: true` with keycloak?

It can be really usefull. Actually it seems not..

Thank you

### Category

Authentication

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by ouafnico** [comment]
Hello

Any idea about this please?

**Comment by Lissy93** [comment]
Heya @ouafnico
So this would be something you'd need to configure through KeyCloak, rather than Dashy. I'm not sure off the top of my head weather it's possible. I've seen this post on the KC forum, but it didn't really have a definitive answer: https://keycloak.discourse.group/t/guest-user-login-through-keycloak/10174
