### ISSUE TITLE
lack of flags in Dashy dashboard rates widget

### ISSUE THREAD

**Issue by TheCommishDeuce** [Lissy93/dashy#1096]
![image](https://user-images.githubusercontent.com/80978749/216598020-91c046eb-4b5f-4beb-8fb5-d4ae13ead207.png)

any idea why flags would not be visible on the widget?
crypto widgets are shown correctly with all the logos but exchange rates are not.
I have tried to route Dashy through multiple VPN locations and the problem persists.

**Comment by sailhenz** [comment]
I have the same issue, I see 404 in console logs. The link to the images might be broken.

**Comment by TheCommishDeuce** [comment]
> I have the same issue, I see 404 in console logs. The link to the images might be broken.

Could you please point me to the place in the logs?

**Comment by ElmerALucier** [comment]
Image links are no longer available for the old urls:
https://raw.githubusercontent.com/transferwise/currency-flags/master/src/flags/eur.png = 404: Not Found

**Comment by Lissy93** [comment]
It looks like Wise has removed their awesome flag repo :(
I'll have a look for an alternative, and try and get an update pushed :)

**Comment by Lissy93** [comment]
PR #1124 updates the endpoint to point to the new repo. Once merged, this should fix the Exchange Rates widget :)

....turns out, there are literally hundreds of currencies - and finding the right flag for each isn't actually straightforward 😅 
I've created [github.com/Lissy93/currency-flags](https://github.com/Lissy93/currency-flags/) and have included (I think) all the main currencies, but let me know if you notice anything I've missed. I'll add some optimizations and docs for it next weekend.
