### ISSUE TITLE
[FEATURE_REQUEST] Open desktop application (Putty, RDP, etc)

### ISSUE THREAD

**Issue by andreapx** [Lissy93/dashy#1099]
### Describe the solution you'd like

It would be awesome if it was possible to launch a particular Putty configuration to connect directly to a server just by clicking on the icon in Dashy, or to connect to a Windows Remote Desktop in the same way.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by PichlAlex** [comment]
this can not be directly implemented in Dashy (as far as i know).
you cannot start directly a EXE from your disk drive for security reasons.
you need to register a protocol handler that starts putty (or any other application)

i implemented this function this way:

- create a Folder (in my case "C:\\Users\\alex\\_myApps\\alex-Protokoll\\")
- Download Auto Hot Key  https://www.autohotkey.com and install it
- adopt "start_rdp.ahk" "start_putty.ahk" to your situation
- compile *.ahk files using Auto Hot Key -> see Documentation
- create a link "start_RDP_link" that executes "%windir%\system32\mstsc.exe"
- adopt "protocol.reg" to your situation
- import "protocol.reg" to windows registry
- try in your browser: alexstartputty://1.2.3.4/   or  with a port:  alexstartputty://some.where.com:25289/
- putty should start and will greet you with a login

content of "start_putts.ahk":
STARTFILE
; get program parameter
parameter = %1%

; remove protocol handler (in this case alexProt:) from parameter
StringReplace, parameter, parameter, alexStartPutty://
StringReplace, parameter, parameter, /

; start putty
run C:\\Users\\alex\\_myApps\\Putty\\putty.exe %parameter%
ENDFILE


content of "start_rdp.ash"
STARTFILE
; get program parameter 1
parameter = %1%

; remove protocol handler (in this case alexProt:) from parameter
StringReplace, parameter, parameter, alexStartRDP://
StringReplace, parameter, parameter, /

; start RDP
run C:\\Users\\alex\\_myApps\\alex-Protokoll\\start_RDP_link.lnk /v %parameter%
ENDFILE

Adopt this "protocol.reg" file to your needs and import this into Windows Registry - this provides RDP, Putty/SSH and open Network Share:
STARTFILE
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\alexStartPutty]
@="URL:alexStartPutty Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\alexStartPutty\shell]

[HKEY_CLASSES_ROOT\alexStartPutty\shell\open]

[HKEY_CLASSES_ROOT\alexStartPutty\shell\open\command]
@="\"C:\\Users\\alex\\_myApps\\alex-Protokoll\\start_putty.exe\" \"%1\""


[HKEY_CLASSES_ROOT\alexStartRDP]
@="URL:alexStartRDP Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\alexStartRDP\shell]

[HKEY_CLASSES_ROOT\alexStartRDP\shell\open]

[HKEY_CLASSES_ROOT\alexStartRDP\shell\open\command]
@="\"C:\\Users\\alex\\_myApps\\alex-Protokoll\\start_rdp.exe\" \"%1\""
ENDFILE

i implemented this because i wanted in Nagios/Icinga a direct action to connect to the host with the current alert....

have fun
