### ISSUE TITLE
Additional pages in Dashy using docker

### ISSUE THREAD

**Issue by PuckeyP** [Lissy93/dashy#1183]
Hi,
Cannot get Dashy to work with multi pages.
I'm using Dashy in a docker container - no special setup. I mount the yml config files to the app/public directory in the container and checked they are present and correct in that location

After extensive search on the internet - Github - Redit - etc, a lot of people seem to have the same problem: the pages are not showing. Even a full rebuild via the GUI does not help.

I, as many others, begin to think this is a bug in the Dashy software. 
What annoys me is that any support on this subject seems to be lacking. Many questions, also about other subjects remain unanswered.

Please give us some guidance how to solve this, or, if it is an unsolved bug remove the functionality. This costs a lot of people way too much time.
PPee

**Comment by zmbcgn** [comment]
Hi, I am running a dashy setup within a kubernetes managed environment and have no problems with extra pages.

You know that you have to reference them in your conf.yml ? They don't appear by itself. 

See: https://dashy.to/docs/pages-and-sections

What I noticed, though, is that the menu items are sometimes not "clickable", most of the time it was because of some syntax error on that subpage.

best regards

**Comment by PuckeyP** [comment]
Thx znbcgn, but I did not forget to refer to the pages in the conf.yml. The pages appear in the home screen , but it does not switch to the pages when you click on it.

**Comment by CrazyWolf13** [comment]
> Hi,
> Cannot get Dashy to work with multi pages.
> I'm using Dashy in a docker container - no special setup. I mount the yml config files to the app/public directory in the container and checked they are present and correct in that location
> 
> After extensive search on the internet - Github - Redit - etc, a lot of people seem to have the same problem: the pages are not showing. Even a full rebuild via the GUI does not help.
> 
> I, as many others, begin to think this is a bug in the Dashy software. 
> What annoys me is that any support on this subject seems to be lacking. Many questions, also about other subjects remain unanswered.
> 
> Please give us some guidance how to solve this, or, if it is an unsolved bug remove the functionality. This costs a lot of people way too much time.
> PPee

Duplicate from https://github.com/Lissy93/dashy/issues/1005

**Comment by zmbcgn** [comment]
@PuckeyP Okay. That behavior I had several times, and it was most of the cases either some syntax error in the yml files (indention mistake or something similar) or I had to run an extra "yarn build" like it is suggested in #1005 .

**Comment by davros1973** [comment]
Hi - I've just started exploring Dashy and I'm also a bit of an idiot lol - but I think I'm seeing these issues too.

I'm not complaining - Dashy is exactly what I need and I think it's amazing that there is so much talent and that people provide their time and effort to make such great solutions.  I thought I'd provide my Dashy-newbie perspective.

I started off with a non-customised Portainer "stack".  That alone was cool!  I loved it how you could quickly get going and see some results.

Then I added a volume mapping for the conf.yml and I seemed able to use the interactive editor and save to disk just fine, and see the updated conf.yml being reflected in page refreshes in different clients.

I tried adding sections and items etc. to get a feel for it.

I new I'd like tabs/pages eventually so I explored that to get a feel of it - and a basic understanding of the options; the paths and the conf.yml entries for it etc.  I tried adding some with volume mappings in the Portainer Stack and by referencing them in conf.yml.

I've retried this sort of thing taking slightly different approaches or additional care ... but generally speaking it seems if I add any pages, then interactive edit no longer seems to necessarily save changes to conf.yml any more.  I couldn't get any interactive edit persisting change with other (local) config yml based pages at all, and I also tried a gist based remote config yml and that didn't seem to work for me at all.

I could make other pages clickable and update their config yml manually and see the change reflected in the tabbed pages.

But ... it seems after some error condition, then that wouldn't necessarily hold true any more.  It seems like some state ... some persistent state (survives container restarts) can become corrupted some how.  e.g. just removing pages and page -references from conf.yml doesn't necessarily restore the ability to save to disk again from interactive edit for the main conf.yml even, even after container restart.  I do have to reset essentially the non-persistent volumes too.

Always to reset, I'd end-up deleting the container (in Portainer) along with non-persistent volumes, and updating the stack (to redeploy) again ... and the the site would work again based on my conf.yml.

--
That's my perception anyway ... but as I've said, I'm often an idiot.  Hopefully it's helpful.

I can make-do for now by creating sections in the main yml with reset volumes and no pages, so that I can cut and paste to other page config yml files, and re-add the pages ... but I lose the convenience of interactive edit and it's just a bit of a faff.

Still - the best dashboard software I've personally discovered, (for me), so far.  Thanks!  :)
