### ISSUE TITLE
[QUESTION] Cancel Cloud Backup

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#128]
Hello again
I tested the cloud function today and I have two questions, again :), once the function is activated, can it be deactivated?

If the password is forgotten, can we, for example, reset and start a new backup?

Thx

**Comment by Lissy93** [comment]
Hey, Good questions!

### How can I Delete my Data?
So I did actually write an endpoint for deleting your data. Using the `DELETE` http method and passing in the backup ID, and a sub-string of the SHA hash of the users password. But I never got round to implementing this into the UI, it's on the todo list, but right now I don't think enough people use this feature to make it high enough priority.

You can still delete your data by sending the request manually (here is [the schema](https://documenter.getpostman.com/view/2142819/TzXumzce) you must know your backup ID and hash your password), or I can delete data manually from the backend from just the backup ID.

### How can I Reset my Password?
In terms of the password- no there can be no way to recover a forgotten password, since the data is encrypted using your password as the key. So (short of cracking AES) it would be impossible to recover data if you forget the password. It was designed like this, because it means you don't need to put any trust in the privacy of the cloud provider (Cloudflare). 

In case you were wondering, this is what the data looks like in the backend - The backup ID (left) is in plain text, but everything else is stringified, encrypted and encoded on the client-side, before being sent to the server:
![Screenshot of backend data](https://i.ibb.co/N6zLbhJ/cf-backend-data.png)

**Comment by EVOTk** [comment]
Thank you very much for these very clear explanations! I understand better how it works.
