### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by zombiehoffa** [Lissy93/dashy#1304]
### Environment

Self-Hosted (Docker)

### System

brave browser on linux and windows

### Version

2.1.1

### Describe the problem

I added 3 clock widgets all with different time zones and all three just display the timezone of the first clock widget I added, even after a rebuild.  Ideally this should show the timezone specified for that particular clock.

![image](https://github.com/Lissy93/dashy/assets/627402/02611d33-ed00-43a2-b3de-56d580515157)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by dacagi** [comment]
Can you try changing "timezone" to "timeZone" with uppercase Z? I've got this working fine in my setup.

`
  - name: International Time
    icon: fad fa-clock
    widgets:
      - type: clock
        options:
          timeZone: Europe/London
          format: en-GB
      - type: clock
        options:
          timeZone: America/New_York
          format: en-GB
      - type: clock
        options:
          timeZone: Asia/Hong_Kong
          format: en-GB

`

**Comment by zombiehoffa** [comment]
Hey that worked thanks! I guess my actual request is then can the program tell me when I'm doing something so trivially stupid rather than start up??

**Comment by dacagi** [comment]
Actually, I must give credit to Lissy93 since this is an awesome repo in regards to [documentation](https://dashy.to/docs/). She has included lots of information, I recommend you have a good look at it, specially [this](https://dashy.to/docs/widgets#troubleshooting-widget-errors) and [this](https://dashy.to/docs/troubleshooting/#how-to-open-browser-console).

Dashy will spit out useful information on the browser console while running, and also, being able to check other logs like the requests being made in the background is important to pinpoint the cause of any issue.

I'm not sure in your specific case if it would have stated something so specific like this property on this file has a typo, most probably no program does that, but you could try separating concerns by removing chunks of your config and testing every section/item by itself in a test yml file. That's what I do before including them in my actual config.
