### ISSUE TITLE
[QUESTION] Background color doesn't seem to be universal

### ISSUE THREAD

**Issue by bobbyl140** [Lissy93/dashy#1443]
### Question

I'm a little confused about how the background variable is working. I am using the Matrix theme (black background), but this same problem happens no matter which theme I use. The background of the page is colored according to the theme, but there seems to be a background somehow behind the page that's this mint green color, which Safari is coloring the tab bar as because that's what it thinks the page's primary color is. 

I have already tried making a custom theme and adding
```css
body {
  background: black;
}
```

Here's a screenshot of what I mean:
<img width="981" alt="Screenshot 2024-01-20 at 12 47 25 PM" src="https://github.com/Lissy93/dashy/assets/61990607/599afc3e-21d0-4625-acc0-4f9b16f30a12">

The effect is also noticeable when scrolling past the top or bottom of the page, the space that lacks content is the same color. Is there anything I can do? Thank you!

### Category

Theming & Layout

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by bobbyl140** [comment]
Update: Never mind, it was a browser extension I use that makes all pages have a dark mode. Sorry for my own failure to see that!

**Comment by bobbyl140** [comment]
Reopening because it's now happening with that extension off. And this time I disabled *every* browser extension just to verify.

**Comment by CrazyWolf13** [comment]
> Reopening because it's now happening with that extension off. And this time I disabled _every_ browser extension just to verify.

Hi @bobbyl140 
As there is very little detail, I have to guess a lot, so please correct me and provide more details.

I think due to the layout of the little screenshot it's an apple device, could be safari?
Layout could be either widescreen phone or ipad, guess ipad.
While I tested with different themes on my dashy instance, I've never noticed such problems.
Could you try with the https://demo.dashy,to and send me screenshots if the issue appears there as well

Please also provide details about what browser and device you are using.

**Comment by bobbyl140** [comment]
Sorry about that. The screenshot in OP is of Safari 17.4 on macOS Sonoma on my MacBook Pro 14". The issue also happens on my iPhone 13 Pro Max, and my iPad Air 4. I attached a screenshot of the demo instance from my MacBook and my iPhone. Notice how on the iPhone screenshot, the top is green (assumed from what Safari thinks is the background), and the bottom of the page beyond the scroll limit is also green. I tested a few Dashy themes and they all do the same thing.
<img width="1468" alt="Screenshot 2024-02-28 at 1 08 00 PM" src="https://github.com/Lissy93/dashy/assets/61990607/b7507459-b5ab-4f3a-a9c4-8ca1c5ae6867">
![IMG_3764](https://github.com/Lissy93/dashy/assets/61990607/cfe5a461-8641-4627-8749-a00cb687fa6b)

**Comment by CrazyWolf13** [comment]
Hi 
Sadly I cannot really test this then.

While searching for the exact color of your image I could find a variable with theme color defined with #00af87 the color that you navbar seems to be.

I can't really troubleshoot this by myself as I do not own apple macbooks, and VM is not really possible due to apple limitations.

IF you are comfortable, could you navigate to dashy's folder and then you should find a file called default.js inside /app/src/utils/default.js inside default.js on line 307 you should find "themeColor: '#00af87', " can you replace that with like a black or blue then rebuild dashy through the GUI ->

![image](https://github.com/Lissy93/dashy/assets/96661824/fb8c1274-475d-4b05-9741-18618dc3b3ce)
![image](https://github.com/Lissy93/dashy/assets/96661824/e505a9df-2e3d-4626-872f-745c460c2f9c) (Recompile or so in English)

Then you should see the changes.

**Comment by bobbyl140** [comment]
Sure enough, that fixes the issue. I set that to `#000000` and now the tab bar is black.

**Comment by CrazyWolf13** [comment]
Hi @Lissy93 
Can we safely change this value? 
Could we make a setting for the user to set this?

**Comment by CrazyWolf13** [comment]
@bobbyl140 

I think for the moment it's best to mount the manifest file.

The fix with chaning the value in default.js was just a temporary fix.

Please create a file on your host with the following contents:
https://raw.githubusercontent.com/Lissy93/dashy/master/public/manifest.json
But change on line 8-9 the theme color variable.

Then mount that file you just created with `-v /path/to/manifest.json:/app/public/manifest.json` make sure to replace /path/to/manifest.json with the path to the file just created.

Add this option to your docker run command and redeploy dashy.

**Comment by bobbyl140** [comment]
I set the value in the `manifest.json` file on my host, added it as a volume, and tore down the container and started it again. Sure enough the green color is gone! Thank you both @Lissy93 and @CrazyWolf13 for the help!

**Comment by Lissy93** [comment]
Yay, nice one @bobbyl140  :)

**Comment by lilynet336** [comment]
@Lissy93 I'm sorry to bother you about this again, but I've just gotten around to getting my containers to auto-update, and am experiencing an issue with the latest version of Dashy while I have the manifest.json mounted as a volume. The Vue build process complains about files with the same name of different cases:

```
Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/app/dist/manifest.json
/app/dist/manifest.json
    at checkSimilarFile (/app/node_modules/webpack/lib/Compiler.js:785:11)
    at writeOut (/app/node_modules/webpack/lib/Compiler.js:984:13)
    at /app/node_modules/webpack/lib/Compiler.js:1014:7
    at arrayIterator (/app/node_modules/neo-async/async.js:3467:9)
    at done (/app/node_modules/neo-async/async.js:3527:9)
    at alreadyWritten (/app/node_modules/webpack/lib/Compiler.js:832:8)
    at processExistingFile (/app/node_modules/webpack/lib/Compiler.js:921:16)
    at /app/node_modules/webpack/lib/Compiler.js:999:10
    at callback (/app/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:202:5)
```

I do not have any Vue experience but I was hoping this would be a relatively quick fix. If I can help at all let me know!

**Comment by lilynet336** [comment]
To clarify: 3.1.0 is the latest version that does not do this.

**Comment by lissy93** [comment]
Ah, I see.

Well this is a Webpack error, so I am going to keep the issue closed, as very very very shortly we'll have migrated to Vite, and issues like this won't happen anymore (re: #2002).

Were you mounting a manifest, right? If so, as a temporary workaround, it will work if you mount to `/app/dist/manifest.json` (instead of `/app/public/manifest.json`) - it's a bit hacky tho.

**Comment by lilynet336** [comment]
Makes sense!

That's correct, yes! That did occur to me to try but I forgot about doing it during my other testing. Thank you for pointing that out!

**Comment by lilynet336** [comment]
Okay so, that unfortunately results in `EBUSY: resource busy or locked, unlink '/app/dist/manifest.json'`, I'll just use the older version until the Vite migration. Sorry to bother you!
