### ISSUE TITLE
[QUESTION] Website will not allow Firefox to display the page ( Pop-Up / iframes )

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#149]
Hello,
I have not used pop-up yet in Dashy. I just tried and it does not work at home.
I am under Firefox 91, under Chrome, it does not work either.

The error is as follows: https://support.mozilla.org/en-US/kb/xframe-neterror-page

![2021-08-12 18_44_38-Window](https://user-images.githubusercontent.com/45015615/129235760-b82b31f5-ca48-4cfa-940c-b0e8ac4575c9.png)

Firefox : 
![2021-08-12 18_44_23-Window](https://user-images.githubusercontent.com/45015615/129235742-caf6271d-8bf7-4087-9ba9-ac8f4c7c3ef2.png)

Chrome : 
![2021-08-12 18_46_17-Window](https://user-images.githubusercontent.com/45015615/129235943-5d63888b-6160-4200-90f5-13db5952b294.png)

This is a configuration problem on my part?

**Comment by Lissy93** [comment]
That would be because the website that you are trying to access doen't have the `X-Frame-Options` header set to `ALLOW`

For any web content to be accessed through an embedded element, it must have the [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) HTTP header set to `ALLOW`. Since [RFC-7034](https://datatracker.ietf.org/doc/html/rfc7034) you will get a `Refused to Connect` error if the header is set to `DENY` (or `SAMEORIGIN` and it's on a different host), but for self-hosted services it is easy to update :)

It should be easy for you to update the headers for the apps you need to access, what web servers are they using?

**Comment by EVOTk** [comment]
Wow, thanks for the quick response, as always!
Indeed, it was enough to edit `"X-Frame-Options" => "DENY` in /etc/lighttpd/lighttpd.conf on PiHole to allow the integration :)

Thanks again !
