### ISSUE TITLE
[BUG] 2.1.1 broke updates

### ISSUE THREAD

**Issue by yuriw** [Lissy93/dashy#1515]
### Environment

Self-Hosted (Bare Metal)

### System

Debian 12

### Version

2.1.2

### Describe the problem

See details here https://github.com/Lissy93/dashy/discussions/1511 and here https://github.com/tteck/Proxmox/discussions/2631

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
Yeah I do know that tteck reverted the lxc version, however this is *NOT* maintained by Lissy or in any way related to dashy.
He just provides an installation script.

Once we have ironed out all the small bugs I will inform him, so he can switch back to the new version.

In the meantime, due to his config dir change it's probably best to create an issue at his repository as that is a problem with his script and not with dashy.

Regarding your request to the config copy, in the proxmox web-gui you can see the lxc id, then you can open a shell on the host proxmox and enter: `pct enter {id}` then you will get a shell from the dashy lxc.

There you can navigate to the folder where dashy is stored, print out conf.yml with cat: `cat conf.yml` and paste it into the new conf.yml on the new host, by editing with nano: `sudo nano conf.yml` you could also copy the file to the new lxc.

If you have anymore questions feel free to reply.

**Comment by p6002** [comment]
When will the bug be fixed?

![image](https://github.com/Lissy93/dashy/assets/74392057/c28c80e2-1479-4120-a6ea-300a199ec43a)

**Comment by CrazyWolf13** [comment]
@p6002 
I'm unsure what the realtion between the original post of this issue and your problem is.

Please share a bit more details, otherwise it's quite impossible to diagnose.
Are you sure you have set the correct read and write permissions?
Has it worked before and now not anymore or is this your first time trying ?

**Comment by p6002** [comment]
I thought it concerned the latest update, which is why I wrote here. 
The dashboard stopped working a few days ago, but now I only have time to diagnose it.
I didn't do anything custom, it is my homepage in the browser. 
I've been using dashboard for a year, it's on a special vm with important stuff that I don't touch until it breaks. 
It is possible that watchtower updated something automatically?
![image](https://github.com/Lissy93/dashy/assets/74392057/8e7b4165-8843-42d0-944a-f630e8db7275)

**Comment by CrazyWolf13** [comment]
> I thought it concerned the latest update, which is why I wrote here. The dashboard stopped working a few days ago, but now I only have time to diagnose it. I didn't do anything custom, it is my homepage in the browser. I've been using dashboard for a year, it's on a special vm with important stuff that I don't touch until it breaks. It is possible that watchtower updated something automatically? ![image](https://private-user-images.githubusercontent.com/74392057/318111960-8e7b4165-8843-42d0-944a-f630e8db7275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Mzc0NzcsIm5iZiI6MTcxMTczNzE3NywicGF0aCI6Ii83NDM5MjA1Ny8zMTgxMTE5NjAtOGU3YjQxNjUtODg0My00MmQwLTk0NGEtZjYzMGU4ZGI3Mjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE4MzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NDRkNGU2ZjE4MzM3ZDcyMzQwYzgwMzdjM2I2MWU5MGY2ZDc2OTM1M2VlZDY3NTViMzk5OWNhMmUyMDllNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-1c5awbXCOsbDsZ3jmsNkW1aTDtS8WaDF-cofBmmkXc)

This issue is regarding an external script on tteck for proxmox, please create a new issue with your details.

**Comment by Lissy93** [comment]
> Once we have ironed out all the small bugs I will inform him, so he can switch back to the new version.

@CrazyWolf13 I don't know too much about Proxmox, but I would _think_ that the 3.0.0 should be good to go / unpin from 2.1.1?

**Comment by CrazyWolf13** [comment]
@Lissy93 thank you for reminding, already had that on the radar as well, i will notify tteck about the changes.
Yeah definitely is good to go, basically proxmox is lxc creator by tteck is just an automated deploy for install from source within I think debian 12.

**Comment by CrazyWolf13** [comment]
Think this has been resolved.
