### ISSUE TITLE
[BUG] Error: ENOENT: no such file or directory, stat '/app/dist/index.html' after shortcut icon set to favicon.ico

### ISSUE THREAD

**Issue by govwin** [Lissy93/dashy#1519]
### Environment

Self-Hosted (Docker)

### System

Debian 12, Docker version 25.0.5, build 5dc9bcc

### Version

Dashy V-2.1.2

### Describe the problem

Each time icon is set to a [favicon URL](http://<ip:port>/favicon.ico), the Dashy crashes.
Web browser shows error: `Not Found`
Docker container log shows: `Error: ENOENT: no such file or directory, stat '/app/dist/index.html'`
After a while everything works again.
Show some different error which either tells to wait or shows a progress. Looks like Dashy rebuilds itself every time favicon URL is included. This rebuild never happens if `hl-<icon>` is the icon.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
Can you be more descriptive than "icon is set to a favicon url"?
I interpret, you add an icon which is a favicon url to a section or item through the GUI editor?

The rebuild is normal and expected, otherwise the changes will not take effect.

`Error: ENOENT: no such file or directory, stat '/app/dist/index.html'`
This error should not appear. 
Make sure you have bind-mounted you conf.yml to your host if using docker.

Then recreate the container with the same conf.yml, then all your settings will stay the same.
This should solve the problem.

If you are using low end hardware like a raspberrypi,  a rebuild may take up to 4 Minutes, so please be patient when changing anything.

**Comment by govwin** [comment]
> I interpret, you add an icon which is a favicon url to a section or item through the GUI editor?

Yes, your interpretation is correct. In the GUI editor, either `Add new Item` or `Edit Item` mode, the value of the `Icon` field is where I put, for example, `http://swing.home:1970/favicon.ico`, where I host my swing-music. 

> The rebuild is normal and expected, otherwise the changes will not take effect.

When I use `hl-<existing icons>` that is applied instantly without any rebuild delay. Dashy has no icon hl-swing. URL icons have rebuild delay but `hl-<existing icons>` builds instantly, is that correct?

`Error: ENOENT: no such file or directory, stat '/app/dist/index.html'` in docker log appears during the `rebuild` delay you mentioned after a URL for icon field is used (and in browser: `Not Found`). After the automatic rebuild, everything works again.

> Make sure you have bind-mounted you conf.yml to your host if using docker.

I don't have to do anything. I just have to wait for the rebuild to complete. But none of the errors indicates that all one has to do is wait for few minutes.

> If you are using low end hardware like a raspberrypi, a rebuild may take up to 4 Minutes, so please be patient when changing anything.

The error in the browser `Not Found` is not helping. If instead it has something like `Please wait, dashy is rebuilding` or something of this sort would have been better.

**Comment by CrazyWolf13** [comment]
> > I interpret, you add an icon which is a favicon url to a section or item through the GUI editor?
> 
> Yes, your interpretation is correct. In the GUI editor, either `Add new Item` or `Edit Item` mode, the value of the `Icon` field is where I put, for example, `http://swing.home:1970/favicon.ico`, where I host my swing-music. 
> 
> > The rebuild is normal and expected, otherwise the changes will not take effect.
> 
> When I use `hl-<existing icons>` that is applied instantly without any rebuild delay. Dashy has no icon hl-swing. URL icons have rebuild delay but `hl-<existing icons>` builds instantly, is that correct?
> 
> `Error: ENOENT: no such file or directory, stat '/app/dist/index.html'` in docker log appears during the `rebuild` delay you mentioned after a URL for icon field is used (and in browser: `Not Found`). After the automatic rebuild, everything works again.
> 
> > Make sure you have bind-mounted you conf.yml to your host if using docker.
> 
> I don't have to do anything. I just have to wait for the rebuild to complete. But none of the errors indicates that all one has to do is wait for few minutes.
> 
> > If you are using low end hardware like a raspberrypi, a rebuild may take up to 4 Minutes, so please be patient when changing anything.
> 
> The error in the browser `Not Found` is not helping. If instead it has something like `Please wait, dashy is rebuilding` or something of this sort would have been better.

That is not fully true.

This error should normally not appear and during a rebuild there is a nice progress bar.
But due to your dashy container being somewhat corrupt it cannot display the nice progress bar and shows this error.

Please bind-mount your conf, delete and recreate your container to fix this issue.

All changes are applied instantly for a preview until the next page reload, while dashy is rebuilding in the background to make them permanent.

**Comment by govwin** [comment]
In my docker-compose yml file I have
```
    volumes:
      - /MyContainerData/Dashy/:/app/public/
```
You have mentioned `bind-mounted` multiple times. Volume is already mounted.
When I was using CASA OS, sure I did see that nice progress bar of Dashy but that never completed successfully. I had to every time recreate the container. Here also I had `volumes` mounted. There was some kind of a problem where I had to recreate the container with the directory mounted sometimes and other times the recreate would work only if I mount conf file directly. No amount of waiting time ever rebuilt the Dashy successfully.
Now I'm using OpenMediaVault containers. Now the only problem is that the nice progress bar never appears. Browser shows `Not Found` and nothing else during the automatic rebuild after URL based icon changes. If I wait for few minutes, then the page works again.

**Comment by CrazyWolf13** [comment]
I have mentioned the bind volumes, to make sure you don't lose your whole config file when rebuilding.
There is currently a a bug where when you are running dashy on low end devices it shows "Possible Error" after the progress bar, which is like a timeout, when it took much longer than expected.

Please mount the conf.yml directly as suggested here, mounting the whole /app/public seems to be related to some issues.
https://dashy.to/docs/quick-start#2-installation


Since I haven't gotten any response to my question, again, does the progress appear if you rebuild? 

Does it happen on manual rebuild (those can be triggered through the gui, on the top right -> Config -> Rebuild) as well or only with the icon?

**Comment by govwin** [comment]
After mounting the `conf.yml` instead of the directories, during manual rebuild, no more `Not Found`. The progress bar appears now.
I'll close this. I'll open a new one if the ever building bug which I had encountered in CASA OS reappears in Open Media Vault.
I guess in my attempt to avoid one problem I created a new problem.
Thanks a lot.

**Comment by CrazyWolf13** [comment]
Great!

Yeah maybe there will somewhen be a new version where there are no rebuilds on each change and fully working folder mounting. For more info see the discussion linked on the release 2.1.2.
