### ISSUE TITLE
[FEATURE_REQUEST] Proxmox usage

### ISSUE THREAD

**Issue by MobilGame06** [Lissy93/dashy#1572]
### Describe the solution you'd like

System usage like Cpu, storage and so on for whole node in proxmox via the api.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by CrazyWolf13** [comment]
Nice idea.
One thing I could recommend here would be to install glances on the proxmox host and then let use the dashy glances widget.

**Comment by MobilGame06** [comment]
yeah i know that this option exists but i like it more to use the build in options

**Comment by Lissy93** [comment]
Hey @MobilGame06 
Just to clarify, do you mean a widget that shows Proxmox resource usage?
Would this be something that you're interested in working on?
I don't currently have a Proxmox instance, but I can add it to the todo list for a later version.

**Comment by MobilGame06** [comment]
sadly i don't have the experience and time for that but it would be nice to be added sometime

**Comment by Lissy93** [comment]
I'm going to close as out of scope for now. Because this functionality is possible via other [resource usage widgets](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#system-resource-monitoring), supporting both Glances, NetData and system (or container) info.

But I'll reopen if many others are interested, or if someone would like to implement this.
