### ISSUE TITLE
[Mobile] Layout tab not showing in portrait

### ISSUE THREAD

**Issue by shadowking001** [Lissy93/dashy#19]
When I open up Dashy on my mobile (Pixel 4a) in portrait view, I can't see the layout config menu :

![dashy_config_tab](https://user-images.githubusercontent.com/43928955/121197978-0e7f9000-c872-11eb-9bbd-996a3db6143a.PNG)

Portrait view :

![Screenshot_20210608-153052](https://user-images.githubusercontent.com/43928955/121198231-44247900-c872-11eb-91f1-598c3294c3a4.png)

If I click on the "+", nothing happens, only the icon is changing :

![Screenshot_20210608-153037](https://user-images.githubusercontent.com/43928955/121198155-34a53000-c872-11eb-8a40-2bd1217eb9f9.png)

Landscape view :

![Screenshot_20210608-152935](https://user-images.githubusercontent.com/43928955/121198370-5e5e5700-c872-11eb-9110-ab2a840a2cc9.png)

When I click on it the tab is correctly being displayed :

![Screenshot_20210608-153003](https://user-images.githubusercontent.com/43928955/121198557-8057d980-c872-11eb-893d-873c078d8c5b.png)

**Comment by Lissy93** [comment]
Thanks for raising this. Yeah it was being hid by a media query, since I initially didn't think there was enough room on smaller screens, but actually the settings really do need to be visible on mobile.

I've implemented a fix, and will put it in a PR with some other fixes and stuff (hopefully) this evening, and I'll let you know when it's merged. 

This is how it will behave after the changes:
[![Screen recording  new meida querys](https://i.ibb.co/Fggm58y/dashy-media-query.gif)](https://ibb.co/6ggrHDT)

**Comment by Lissy93** [comment]
This is fixed now :)
