### ISSUE TITLE
[QUESTION] What are the recommended specs for Demo1

### ISSUE THREAD

**Issue by RocketNinja15** [Lissy93/dashy#197]
Hi!

I’m really interesting in setting up my own server, and I was wondering what the recommended specs for Demo1 would be. If I were to put most of those on it, would a RaspberryPi with a bigger memory card work? How about an old Mac Book Pro?

Also, is there a list of recommended selfhosted plugins like in Demo1?

Thanks!

**Comment by Lissy93** [comment]
Hey @RocketNinja15 - Welcome to Dashy 👋 It's great to have you here.

I'm not sure if I am understanding your question correctly, do you mean what are the specs required for hosting Dashy, or the specs required for running the services seen in Demo 1?

If it's the first, then providing your machine is reasonably modern (within the past 5-ish years), you shouldn't have any issue running Dashy. I have it running on a Pi 3, along with Pi-Hole and a bunch of other apps, with no issues at all. But when the app first builds, the Docker container is a bit RAM-hungry as all data is copied into memory while it compiles.
I am working on a strip-downed lite-weight version at the moment, which will almost completely mitigate this issue, by Lighttpd instead of the Node.js server. That'll come out in the next week or two.

For Dashy, in an ideal world, I would recommend:
- 2GB of memory
- 1GB or more of free disk space
- Core i3 or equivalent or faster

If you mean the services in the example demo, then you will need a decent machine. I would guess that your Macbook Pro should be fine, but don't quote me on that. Some apps, like Plex obviously need a lot of disk space if you have a ton of movies ets. And most of the apps are designed to be running 24/7, which makes a laptop not always an ideal candidate. You're best option would be to start small, run the apps that you need, and get familiar with Linux and server maintenance then upgrade once you've outgrown your current hardware.  I think forums, Discord or Reddit may be better places to ask more general questions like this, but it's worth trying things out yourself first.

Hope that helps :)

**Comment by RocketNinja15** [comment]
> 
> 
> Hey @RocketNinja15 - Welcome to Dashy 👋 It's great to have you here.
> 
> I'm not sure if I am understanding your question correctly, do you mean what are the specs required for hosting Dashy, or the specs required for running the services seen in Demo 1?
> 
> If it's the first, then providing your machine is reasonably modern (within the past 5-ish years), you shouldn't have any issue running Dashy. I have it running on a Pi 3, along with Pi-Hole and a bunch of other apps, with no issues at all. But when the app first builds, the Docker container is a bit RAM-hungry as all data is copied into memory while it compiles.
> I am working on a strip-downed lite-weight version at the moment, which will almost completely mitigate this issue, by Lighttpd instead of the Node.js server. That'll come out in the next week or two.
> 
> For Dashy, in an ideal world, I would recommend:
> 
>     * 2GB of memory
> 
>     * 1GB or more of free disk space
> 
>     * Core i3 or equivalent or faster
> 
> 
> If you mean the services in the example demo, then you will need a decent machine. I would guess that your Macbook Pro should be fine, but don't quote me on that. Some apps, like Plex obviously need a lot of disk space if you have a ton of movies ets. And most of the apps are designed to be running 24/7, which makes a laptop not always an ideal candidate. You're best option would be to start small, run the apps that you need, and get familiar with Linux and server maintenance then upgrade once you've outgrown your current hardware. I think forums, Discord or Reddit may be better places to ask more general questions like this, but it's worth trying things out yourself first.
> 
> Hope that helps :)

Thanks so much! I meant both, and I wasn't clear. Sorry about that! Your answer perfectly solved it! Thank you!

**Comment by Lissy93** [comment]
For Lighttpd it definatley won't be any more than above. Should run tottally fine on a Pi 3 for example. 
There is a spike in memory usage when the app is first built, before it drops to steady level again, so that's worth keeping in mind.

**Comment by Lissy93** [comment]
Hmm okay yeah, so that would be using the Node server, so 300 is not unusual.
I'm going to make a lite version of the Docker container, using just NGINX instead of Node, which I think should be much lower-resource. Only problem is that some of the functionality (writing YAML to disk and status checks) require server-side code, which is what the Node server was originally chosen.
