### ISSUE TITLE
[BUG] down arrow blocking alt text for links

### ISSUE THREAD

**Issue by Xilisys** [Lissy93/dashy#232]
### Environment

Self-Hosted (Docker)

### Version

1.8.0

### Describe the problem

On hovering over an item on the dashboard, the alt-text pops up. There is a down arrow symbol blocking part of the text. This occurs on all alt-text popups.
![Capture](https://user-images.githubusercontent.com/794094/133824930-e5e6a3e7-7ffd-465d-9ed7-9d36982595f8.PNG)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Thanks for that, and the clear description + screenshot. That is indeed a bug, and I'll get a fix done and pushed this weekend :)

**Comment by Lissy93** [comment]
Fixed in #234 which will be released sometime this evening, in version 1.8.1.

Tooltip arrows are now in the correct place, and the status indicator + opening method no longer overlap. Made a couple other improvements to the tooltip at the same time, so it should now look something like this:
<p align="center"><img width="400" src="https://user-images.githubusercontent.com/1862727/133897339-681b3eb8-82d4-4fd5-aabf-7170b35bef2e.png" /><p>

Thanks for raising, and feel free to reach out if you need any more support,
Cheers, Alicia :)
