### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by double-square** [Lissy93/dashy#244]
Why don't simpleicons load?
![error screenshot](https://i.imgur.com/KymlcPX.png)

**Comment by Lissy93** [comment]
Hi, Simple-Icons works fine. But I cannot help you if you do not provide the requested info. 

Please first check your config against the docs. If your still facing problems, then you need to share your config file, the output of any errors in the browser console, and details about your environment. Redact any personal info before uploading. In the future, please also follow the issue template, and complete the title and all relevant fields. 

Keeping issue closed due to lack of info / potential spam.
