### ISSUE TITLE
[QUESTION] statusCheck refresh ?

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#35]
Hello,
With the help of the following documentation, I set up "statusCheck " : https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md

Dashy is installed in docker (via docker-compose) on a Debian 10.

However, I have some questions about how it works.

- For example, on Jackett it does not work, the ping returns:
`{"successStatus":false,"message":"âŒ Service Unavailable: Server resulted in ERR_FR_TOO_MANY_REDIRECTS "}`
My adress to Jackett is : http://192.168.2.42:9117/UI/Dashboard
**Do you know how to solve this problem?**

- I also have a problem for pinging the proxmox interface which is in https but for which I do not have a certificate because I use the local address: https://192.168.2.40:8006
The ping returns: `{"successStatus":false,"message":"âŒ Service Unavailable: Server resulted in UNABLE_TO_VERIFY_LEAF_SIGNATURE "}`
**Is it possible to disable certificate verification?**

- If the dashboard is already open and a service becomes unavailable, the status light does not change. **There is no automatic refresh?**

Thank you very much for your work, I discovered Dashy and I found him really good!

**Comment by Lissy93** [comment]
Hmm, thanks for raising this- I've not seen that response before from any of my services. Usually `ERR_TOO_MANY_REDIRECTS` is an issue with the client (system or browser), or an error in the application setup, but in this instance I think it might be trying to redirect the request to an authentication page, or [something similar](https://github.com/linuxserver/docker-jackett/issues/100). What response do you get if you just send a GET request to that URL with Postman? 

The second error message `UNABLE_TO_VERIFY_LEAF_SIGNATURE` is, as you said because of the SSL certificate. A short-term solution would be to set `NODE_TLS_REJECT_UNAUTHORIZED=0` and an env var when you run the app, although that will then be applied to all requests made through Dashy and isn't great in terms of security. A better long term solution would be for me to add an attribute under `item`, to enable the user to add custom headers to their request, and then you'd be able to specify your auth token, or whatever is needed for that particular app.

> If the dashboard is already open and a service becomes unavailable, the status light does not change. There is no automatic refresh?

Correct, right now there isn't, tbh I hadn't thought about that, but it's a good idea. It would be easy to implement, so I'll add it to my todo list, and try and get that done this next week :) I'll keep this issue open, and let you know when that's done.

**Comment by EVOTk** [comment]
Thx for your reply !

For `Jackett`
On another machine I did a clean install of dashy and jackett, the problem is still present, I think it comes from Jackett. I am not familiar with all of this, but I installed Postman in order to get as much information as possible.

Here is the reponse provided by Postman, on a GET request to Jackett : 
[response.txt](https://github.com/Lissy93/dashy/files/6664698/response.txt)

--

For `UNABLE_TO_VERIFY_LEAF_SIGNATURE`
Indeed, I think that the ideal would be to be able to choose on a case-by-case basis whether you want to disable certificate verification or not.

--

Thank you for this feedback :) It would be really nice to have an automatic refresh!

--

I allow myself one more remark, do you think that it would be possible to provide a function so that the healcheck is executed if necessary on a url other than that of the service?

Example:
For Plex, I want the click to be redirected to https://plex.tv/web, but that the healthcheck monitor "http: 192.168.1.42: 32400"

Sorry for my english, i'm french, and i use google translate :(

**Comment by Lissy93** [comment]
> do you think that it would be possible to provide a function so that the healcheck is executed if necessary on a url other than that of the service?

Yeah, that would certainly be possible, I think it's a good idea actually, because some self-hosted services have a dedicated endpoint for healthchecks. I will get try and that implemented some time this next week, along with an option for custom headers, and a refresh rate  :)

**Comment by EVOTk** [comment]
Thank you very much, I will look forward to this.
Again thank you for your work.

**Comment by Lissy93** [comment]
Implemented in 8eeadbc98ffb554a40ad50d1cd6ae612e8e9a355 or PR #52, which I'll merge this evening :)
You can now add `statusCheckInterval` under `appConfig` to an integer, in seconds and the status of your services will be checked at that interval. E.g. to check every 20 seconds:

```yaml
appConfig:
  statusCheck: true
  statusCheckInterval: 20
```

**Comment by EVOTk** [comment]
> The second error message `UNABLE_TO_VERIFY_LEAF_SIGNATURE` is, as you said because of the SSL certificate. A short-term solution would be to set `NODE_TLS_REJECT_UNAUTHORIZED=0` and an env var when you run the app, although that will then be applied to all requests made through Dashy and isn't great in terms of security. A better long term solution would be for me to add an attribute under `item`, to enable the user to add custom headers to their request, and then you'd be able to specify your auth token, or whatever is needed for that particular app.

Please don't forget me for this :) Would you like me to open a new issue for this concern?

**Comment by Lissy93** [comment]
Ah sorry, I had forgotten, I will address this this afternoon and get back to you here :)

**Comment by RickyChan21** [comment]
Hello @EVOTk have been able to fix the issue with jackett statuscheck displaying ERR_FR_TOO_MANY_REDIRECTS?

**Comment by EVOTk** [comment]
Hello,
No, but in the end I didn't search much because I no longer use Jackett. I now use Prowlarr which doesn't have this problem.
