### ISSUE TITLE
[FEEDBACK] integrate dashy with Authentik or Authelia OpenID

### ISSUE THREAD

**Issue by Akruidenberg** [Lissy93/dashy#385]
I see in the documentation that Dashy supports keyclock. However, I would like to integrate Dashy with my Authentik OpenID provider. Is there general OpenID support for Dashy?

Thanks in advance!

**Comment by Lissy93** [comment]
Yup, I believe you can use OIDC [with KeyCloak](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sso-protocols/oidc.html). 

Alternatively, is it possible to use OpenID directly [with NGINX](https://www.nginx.com/blog/implementing-openid-connect-authentication-kubernetes-okta-and-nginx-ingress-controller/). Not too familiar with Authentik myself, but their docs [have some examples](https://goauthentik.io/docs/providers/proxy/forward_auth) which might be of help.

**Comment by Akruidenberg** [comment]
I'm running Authentik, not keycloak. I would like to use the multi user option with a OpenID provider like Authentik.

**Comment by Lissy93** [comment]
Do Open ID providers not integrate within KeyCloak?

**Comment by Akruidenberg** [comment]
I don't know.  But keycloak is more Popular I think.

**Comment by Lissy93** [comment]
I think for now, I won't be implementing Authentik nativity into Dashy. Just because there are so many authentication providers, so it would be hard to support them all. KeyCloak is a good catch-all solution, as it supports most auth protocols. Authelia, and other NGINX-based methods also work with Dashy, and there's a built-in basic auth feature too.

If things change in the future, I'll update you here on this ticket. Or if you manage to get it working, do let me know what the process was :)

**Comment by vgwizardx** [comment]
So if you are using Cloudflare Zero Trust Tunnels you can add SSO to Dashy using this method. [https://blog.wains.be/2023/2023-01-07-cloudflare-zero-trust-authentik/](https://blog.wains.be/2023/2023-01-07-cloudflare-zero-trust-authentik/ )@Lissy93 might want to add this to your documentation as I found this super easy to set up, especially if you are already using Zero Trust Tunnels.
