### ISSUE TITLE
[FEATURE_REQUEST] Disallow displaying config

### ISSUE THREAD

**Issue by mfnalex** [Lissy93/dashy#455]
### Describe the solution you'd like

Hi, I'd like to have an option to disallow viewing the yaml config from the browser. Although it doesn't contain any sensitive information, I don't like the idea of people just being able to see and download it.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Maybe

**Comment by Lissy93** [comment]
Definitely possible, just something to keep in mind: If you don't have any auth, then even if the config is hidden then it will still be able to be viewed through the dev tools, since it's required for rendering the data.

I will add this to the todo list :)

---

In the meantime, if anyone would like to pick this up, here's some info as a starting point:

First add a new item to the config (e.g. `appConfig.disableViewConfig`) - [here's a guide](https://github.com/Lissy93/dashy/blob/master/docs/development-guides.md#adding-a-new-option-in-the-config-file).
Then add `v-if="!appConfig.disableViewConfig"` to the view config buttons (in [`ExportConfigMenu.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/InteractiveEditor/ExportConfigMenu.vue#L10) and [`ConfigContainer.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/Configuration/ConfigContainer.vue#L7)). Finally, just check it works as expected.

**Comment by Lissy93** [comment]
I've implemented this in #488 (released in V2.0.3) - Set `appConfig.disableConfiguration: true` to try it out :)
With this option set, the user also won't be able to make any changes to the config.

But remember, that digging through the dev tools, the user will still be able to see any part of the config that is rendered anywhere on the page. So if you've got anything sensitive there, then make sure your dashboard is adequately secured with authentication/ behind a firewall

**Comment by mfnalex** [comment]
Thanks :) As said, there's nothing sensitive, I just felt it was a bit wrong to show it to users who don't have a way of changing it anyway! Seeing it in dev tools is no problem at all! :)
