### ISSUE TITLE
[FEATURE_REQUEST] New page

### ISSUE THREAD

**Issue by QuentinLeSonne** [Lissy93/dashy#466]
### Describe the solution you'd like

Hello
I come to see you because I use the Dashy as an application dashboard and the page is already full
I would therefore propose to create a second page which could be in the menu, next to "home" or "about"
On this second page, we could modify it like the main one in order for example to have an app dashboard and a graph dashboard

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Heya, 
Multi-page support is planned, you can checkout out the [Roadmap](https://github.com/Lissy93/dashy/discussions/405) for upcoming features.
And I agree, this feature is very important, I too am having to run three instances of Dashy, just to have three dashboards. The delay in implementing is because there's a bit of complexity involved.
I will come back here and update you once it's done (probably sometime in the Spring)
Thanks :)

**Comment by QuentinLeSonne** [comment]
Thank you for your quick and efficient response, so I'm looking forward to this new feature! :)
