### ISSUE TITLE
[BUG] Dashy gets "EPROTO (-71)" error or "Request timed out" on statuscheck of a non-standard port for an http target

### ISSUE THREAD

**Issue by ikidd** [Lissy93/dashy#527]
### Environment

Self-Hosted (Docker)

### Version

2.0.3

### Describe the problem

Specify an item with:

      - title: Portainer Mail
        description: 'Portainer: Mail/NCP'
        icon: hl-portainer
        url: http://10.10.251.13:9000
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_1509_portainermail

This gives the EPROTO (-71) error

or

      - title: Gitea
        icon: hl-gitea
        url: http://http://10.10.251.9:3030
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 2_1509_gitea

This gives "Request timed out"

An item with standard port without an appended :<portnumber> works fine.

### Additional info

I tried to find an issue in the axios library used for the request but it looks like that library should be capable of getting true responses from http requests to a non-standard port.

Running in docker-compose: 

    version: "3.5"
    services:
      dashy:
      # To build from source, replace 'image: lissy93/dashy' with 'build: .'
      # build: .
      image: lissy93/dashy
      container_name: Dashy
      # Pass in your config file below, by specifying the path on your host machine
      volumes:
        - ./conf.yml:/app/public/conf.yml
      ports:
        - 4000:80
      # Set any environmental variables
      environment:
        - NODE_ENV=production
      # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      #  - UID=1000
      #  - GID=1000
      # Specify restart policy
      restart: unless-stopped
      # Configure healthchecks
      healthcheck:
        test: ['CMD', 'node', '/app/services/healthcheck']
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by ikidd** [comment]
Starred repo and reopened issue.

**Comment by Lissy93** [comment]
Sounds like Cors error, could you share the console output? Have [you tried this](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#status-checks-failing)?

**Comment by Lissy93** [comment]
Okay, reopened as requested, but I don't think this is a bug with Dashy, just a Cors error. Take a read of the  [status insidicators docs](https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md)

Some things you can try (depending on the error message you get in the console) 
- Disable ssl checking, with `statusCheckAllowInsecure`
- Set custom response accept code, with `statusCheckAcceptCodes`
- Pass in any required headers in `statusCheckHeaders`
- Set correct headers on origin 
- Use an alternate URL for checking, with `statusCheckUrl`
- Ensure the URL is correct and is fully formed with the protocol.
- Try the endpoint in postman, like: `https://[url-of-dashy]/status-check/?&url=[service-url]`
- If all that fails, you'll have to create your own ping service that exposes a page with 200, since ping-only status checks not yet supported 

I'm afk at the moment, but more details can be found in [this guide](https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md#troubleshooting-failing-status-checks)

---

For future reference, please include logs, check previous issues, the troubleshooting guide and docs before ticking those checkboxes.

**Comment by ikidd** [comment]
I had tried pretty much all of those before I opened the ticket.  Confirmed the Portainer login page returned 2XX headers, and you can see I had put in the AllowInsecure flag as well.  I tried other pages, like that Gitea item I also included that doesn't work, but gets a different response.

Sorry to waste your time, I'll close the ticket.

**Comment by Lissy93** [comment]
I've just noticed that for the GitTea one, you've got 2x `http://http://` before the URL, which is maybe the issue. 

And for the other service, do you get the same result in postman using the status check endpoint?

**Comment by ikidd** [comment]
> I've just noticed that for the GitTea one, you've got 2x `http://http://` before the URL, which is maybe the issue.
> 
> And for the other service, do you get the same result in postman using the status check endpoint?

Actually, I had noticed that one as I pasted it into the bug report, went back and fixed it and tried it out with no improvement, but forgot to fix it in my bug report before I posted.

So I open up dashy this morning to take another look, and it's all working as soon as I opened it.  I made a couple of new items on non-standard ports hosted on the same server, all status checks come back correctly.

I have no idea why, I changed nothing from when I posted and closed the ticket up last night.
