### ISSUE TITLE
[QUESTION] checking the logs

### ISSUE THREAD

**Issue by lgwapnitsky** [Lissy93/dashy#531]
### Question

I'm receiving an error on the pi-hole-stats widget that says to check logs, but I do not see where the logs are located. Dashy is on bare-metal.

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
The logs you need are in the browser console, [here's instructions](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) for opening, it's usually <kbd>F12</kbd>.

It will most likely be a CORS error, which can usually be fixed with [one of these methods](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#widget-cors-errors). 

Hope that helps :)

**Comment by vanillanesquik** [comment]
> lgwapnitsky

Were you able to get this working? I am also having issues with widgets that require API keys.

I have tried the useProxy: true with no luck.

Running Dashy on Docker in Unraid. Thanks

**Comment by lgwapnitsky** [comment]
Yes. Pihole worked fine. Working on my anonaddy now

**Comment by Lissy93** [comment]
Okay, thanks for the update :)
Closing...
