### ISSUE TITLE
[FEATURE_REQUEST] Email notification when a service is down

### ISSUE THREAD

**Issue by AC-WhiteGlint** [Lissy93/dashy#580]
### Is your feature request related to a problem? If so, please describe.

Hi,

First thank you for this wonderfull piece of software, it is very handy and easy to use.

Regarding the http status check, it would be great if you could implement an email notification when a service is down.

I do not want to deploy heavier monitoring tool, as they will be way too much for my use case.

### Describe the solution you'd like

A simple email notification with the service name when a service is seen as down.

### Priority

Medium (Would be very useful)

**Comment by AC-WhiteGlint** [comment]
Let's reopen this!

**Comment by Lissy93** [comment]
Hi @AC-WhiteGlint

Unfortunately, the way the app works means this isn't really possible. Since status checking happens on the client-side, it's triggered from the browser and stops when you close the window (so there aren't thousands of requests happening when you're not using the app). Dashy isn't intended to be an uptime monitor so I think this feature is a bit out of scope. Also building email notifications, is going to greatly increase complexity and attack surface.

I would recommend using a dedicated application, like [Uptime Kuma](https://github.com/louislam/uptime-kuma). 
Alternatively write a simple script to periodically ping a list of endpoints and trigger an event when one is repeatedly down.

But if you're really set on doing this in Dashy, then feel free to fork the project and add it yourself. Here's a starting point:
- First move status checking server-side
- Setup a database (e.g. Reddis) to store recent history (so that multiple failed requests can be detected)
- Then configure a mail server, secure it and interact with it from the Node server (or use a third-party service for notifications)
- Finally just put it all together

**Comment by vbariteau-mwb** [comment]
Thank you @Lissy93, I went with uptime-kuma which better suits my needs!

**Comment by Lissy93** [comment]
Uptime Kuma is awesome, good choice :)
I'm gonna close this ticket now....
