### ISSUE TITLE
[QUESTION] Is it possible to use semver on  the docker image?

### ISSUE THREAD

**Issue by lcotonea** [Lissy93/dashy#61]
Because I use dashy through a helm chart which is versioned, could you please at lease use version for the docker image?
Many thanks for your answer

**Comment by Lissy93** [comment]
Sure, I actually just implemented the versioning in #57 so the next Docker release should be tagged, if it isn't already :)

**Comment by Lissy93** [comment]
So Docker Hub is automatically fetching fresh releases whenever a branch is merged into master. I'm not quite sure how to configure it so that DH will also tag each release with the current version. Have you done it before? Got any ideas on how to do this?
I'm guessing I need to scrap the DH integration, and write a GH action which will provide more flexibility. This was the first time I containerized a web app, so I'm a bit of a noob at it

**Comment by EVOTk** [comment]
Hello,
I think you need to create the releases on GitHub from master, for example V1.0.0, V1.0.1, ...
![2021-06-25 18_20_52-EVOTk_dashy_ 🚀 A dashboard for your homelab](https://user-images.githubusercontent.com/45015615/123456396-16199580-d5e3-11eb-8d02-e8adb04c71d7.png)

then configure in dockerhub to monitor this ( Scenario / Match versions )
![2021-06-25 18_27_31-Docker Hub](https://user-images.githubusercontent.com/45015615/123456473-2af62900-d5e3-11eb-9331-226e1e9c4ca5.png)

**Comment by Lissy93** [comment]
Thank you @EVOTk 🙌  you saved the day again 😄  
Dashy now has releases, here's the [first one on Docker Hub](https://hub.docker.com/layers/155765870/lissy93/dashy/release-1.3.6/images/sha256-ddf2a970a2a3efcda70db694f4064ffcf703297b4063fb2c1eb3096a2af236bd?context=explore)
Hope that helps you @lcotonea

**Comment by lcotonea** [comment]
Many thanks! It's perfect
