### ISSUE TITLE
Self singed SSL problem after upgrade

### ISSUE THREAD

**Issue by GogoFC** [Lissy93/dashy#683]
### Question

Hello

Using docker compose with a self signed cert.

After I upgrade from V 2.0.3 to any newer version I can't connect to Dashy in Browser.

On version 2.0.3 logs I get ` HTTPS server successfully started (port: 443 of container)` , I don't see that message after upgrading.

Volumes are all OK I checked the location of certs inside container at `/etc/ssl/certs/` they're there. 

If the certs weren't there I think there would be error `SSL Not Enabled: Public key not present1` , I don't get that error so I guess it read the certs.

I checked for ports running inside container and I don't see port 443 anymore.

```
tcp        0      0 127.0.0.11:37203        0.0.0.0:*               LISTEN      -
tcp        0      0 :::80                   :::*                    LISTEN      63/node
```
What could I look into.

**Comment by GogoFC** [comment]
bad bot

**Comment by Lissy93** [comment]
Hiya @GogoFC 
Sorry about that, it's helpful to know that it was 2.0.4 onwards that it stopped working, as that must have been caused by #528 

All the SSL stuff happens in [`/services/ssl-server.js`](https://github.com/Lissy93/dashy/blob/master/services/ssl-server.js), which wasn't modified, so the only thing I can think could of caused it would be [this line](https://github.com/Lissy93/dashy/pull/528/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L42) 🤔

**Comment by IamJovenD** [comment]
Hi, sorry I encounter the same issue. What should be a work around? Thanks

**Comment by GogoFC** [comment]
2.1.0 fixed it. Thanks.
