### ISSUE TITLE
[BUG] HealthCheck is not working for docker without healthcheck and non docker apps

### ISSUE THREAD

**Issue by ranrinc** [Lissy93/dashy#689]
### Environment

Self-Hosted (Docker)

### Version

2.0.9

### Describe the problem

I try all my docker containers with health checks that will run perfectly and show the status. However, non-docker nor those apps without health checks will come back `Cannot GET /status-check/` or RED.

Any idea what I did wrong? 

For example: portainer will show RED even though I put in the correct IP with port

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by asenov** [comment]
I've seen this problem when I add a URL without a protocol.

Examples
yahoo.com - not working
https://yahoo.com - it's good

**Comment by Lissy93** [comment]
Hi @ranrinc 
Sorry, I totally missed this ticket.

The reasons why, and solutions for failing status checks are here:  [**Docs → Troubleshooting Guide → Failing Status Checks**](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#status-checks-failing).

You will have an error message in the [browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console), which will also point you in the right direction.
I recommend you also take a look at the [Status Checks](https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md) docs, which explains things further.

---

But since some of your status checks are working, I'm fairly certain that this is not an issue with Dashy, and since there's not enough info to diagnose, I'm gonna close out this ticket. In the future, pls try and check the troubleshooting, docs and previous tickets before opening a new one.
