### ISSUE TITLE
displayData ignored

### ISSUE THREAD

**Issue by shadowking001** [Lissy93/dashy#7]
Hello, first let me thank you for this shiny dashboard, I really love the whole feeling.
I'm struggling with how to customize frames with _displayData_. Here is my config tree :

![dashy_disp_bug_1](https://user-images.githubusercontent.com/43928955/119812622-9e275500-bee8-11eb-87ad-3262adb14e86.PNG)

The YAML version :

![dashy_disp_bug_2](https://user-images.githubusercontent.com/43928955/119812737-c020d780-bee8-11eb-95d8-4762c3854538.PNG)

I would expect the "Informations" frame to have a 4x1 format with large icons, but nothing changes when I save the config :

![dashy_disp_bug_3](https://user-images.githubusercontent.com/43928955/119813047-1d1c8d80-bee9-11eb-9c27-deeca6b97394.PNG)

PS : Btw there is a wording mistake, the message says "Changes s**e**ved successfully"

**Comment by Lissy93** [comment]
Thanks so much for raising this. 

The issue is in fact my bad documentation, as I didn't really explain it well.
The rows and columns are in fact as a proportion of screen width / height, rather than by number of items within each tile. It's because I'm using [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) to make the page responsive.

For example:
![Example of rows and cols](https://i.ibb.co/HXRWVRK/how-rows-and-cols-work-in-dashy.png)

By default, on most screens there will be 4 columns, but large screens will have 5, and small will have 3 or 2 (depending on how much space there is), and small mobiles will just have 1. Rows are dynamic depending on how much content you have divided by number of columns. 

In the meantime I'll update the docs, but in the future I would like to make the whole process much more intuitive. I'd not thought about measuring each section by number of items, as you expected, but I think that's a great idea :) And sorry for the confusion

P.s thanks for spotting the typo in the pop-up message, I've fixed that now :)

**Comment by Lissy93** [comment]
Hey @shadowking001

Just to let you know, I've added some new data attributes that will fix this for you in #8 (specifically 10ec99d7426237c83977244debbc08043354fa1e). 

Under `displayData` for a given section, you can now specify `layout: grid`, and they use `itemCountX` to set how many items will display horizontally, and optionally `itemCountY` to do the same vertically. 

Don't forget to update to the latest version. Hope that helps :)

**Comment by shadowking001** [comment]
Thanks a lot I'll look into it in the coming days. 👌
