### ISSUE TITLE
FontAwesome Icons[QUESTION] <title>

### ISSUE THREAD

**Issue by gpalsingh30** [Lissy93/dashy#726]
### Question

I am trying to use free "font awesome" icons but are not rendering. For example, "fa-solid fa-font-awesome"
Categories like fa-solid, fa-brands etc are not rendering but fas, fab etc are working.

### Category

Using Icons

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by laye0619** [comment]
same question here

**Comment by Lissy93** [comment]
See the troubleshooting docs, specifically: **[Font Awesome Icons not Rendering](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#font-awesome-icons-not-displaying=)**

**Comment by Lissy93** [comment]
Have closed this ticked, as it's not clear from your question what you're asking. But feel free to reply if you still need help.

Font Awesome icons are specified by `[category] fa-[icon-name]`, so that's what you'd need to put in your config.
Please see for **[Docs → Icons → Font Awesome](https://github.com/Lissy93/dashy/blob/master/docs/icons.md#font-awesome=)** for more info, as well as previous tickets and the troubleshooting guide.

As per the FA docs, the available categories are `fas` (solid), `far` (regular), `fal` (light), `fad` (duotone) and `fab` (brands). You can search for available icons on the [FA Website](https://fontawesome.com/v5/search), then just copy / paste the code.
For example: `fab fa-raspberry-pi`, `fab fa-linux`, `far fa-unicorn`, `far fa-rocket`, etc.

All icons from [Font Awesome V5](https://fontawesome.com/v5/search) are supported, but you must specify your API key if it's a premium icon (under `appConfig.fontAwesomeKey`). Also ensure that Font Awesome is enabled, with `appConfig.enableFontAwesome: true`.
