### ISSUE TITLE
[FEATURE_REQUEST] APOD widget custom instance/local scrapper

### ISSUE THREAD

**Issue by k073l** [Lissy93/dashy#735]
### Is your feature request related to a problem? If so, please describe.

It seems that the 'official' APOD API is [dead](https://github.com/PawelPleskaczynski/apod_api/issues/11) and I can't get the [widget](https://dashy.to/docs/widgets#astronomy-picture-of-the-day) to work.

### Describe the solution you'd like

From a quick glance at the [Dashy code](https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/Apod.vue#L42) I don't see an option for a custom instance. The [code](https://github.com/PawelPleskaczynski/apod_api) for the 'official' instance is public and it might still work. Another solution would be to have a local scrapper of the NASA website in Dashy, rather than relying on an API.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
The API wrapper is indeed down. And I did just try and deploy my own instance to Heroku, but seems it would take a bit of work to get it working. And NASA's official APOD API is a bit of a pain to use, it requires an API key, needs to be proxied, and doesn't even return the actual image.

That said, scraping is absolutely not the way to go. It's against NASA's ToC, and definitely out of scope for this project.


Possibly the best option would be to remove this widget instead of fixing it, as the functionality can probably be used through one of the dynamic widget options instead. E.g. the [Iframe widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#iframe-widget=), [Image widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#image=), [Embed widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#html-embedded-widget=) or maybe the [RSS Widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#rss-feed=) with `https://apod.nasa.gov/apod.rss`

**Comment by k073l** [comment]
Iframe seems to be not working for me. Tried it on Firefox, but it got blocked since it was an embed. Tried on different browsers and devices, but then it was not rendering at all. 
As for the RSS Widget it could work, but from what I've seen in the XML, it returns a small resolution picture (60x40, not ideal). 
Image Widget wouldn't work, as the image on website has a distinct name (SomeName.jpg rather than apod.jpg). 

Finally, I tried Embed Widget. Created an iframe with the APOD address (in options: html), but same situation as with the regular Iframe Widget. There's no JS to link to on the website (apart from tracking one). 
Maybe it could be achieved with putting the JS oneself (the options: script, rather than scriptSrc), but I don't know how.

**Comment by Lissy93** [comment]
I've rebuilt the old API, which is available here: [Lissy93/go-apod](https://github.com/Lissy93/go-apod). When I get a moment, I'll update the APOD widget to use that new service. Or, if you'd like to submit a PR, then that would be awesome!

In the meantime, I also made a raw image endpoint, that you could use with the [image widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#image), it's [`https://go-apod.herokuapp.com/image`](https://go-apod.herokuapp.com/image).

Hope that helps :)

**Comment by k073l** [comment]
Very helpful, thanks.
I submitted a PR, which updates the APOD Widget with the new API.
Thanks for all your help.
