### ISSUE TITLE
[BUG] The material theme customization does not work like the rest

### ISSUE THREAD

**Issue by Entropy-9973** [Lissy93/dashy#744]
### Environment

Self-Hosted (Docker)

### Version

2.1.0

### Describe the problem

When I change the Background-Darker value on the Material theme preset, it does not change the color of the nav bar like the rest of themes (Where it works fine).
Can you please suggest a temporary quick fix until the bug is fixed ?

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Try clicking "Show All Variables" in the theme configurator

**Comment by Lissy93** [comment]
Heya @Entropy-9973 

So the way the themes work, is that all the colors are defined as CSS variables, so they can be overridden. Here's the [full list of variables](https://github.com/Lissy93/dashy/blob/master/src/styles/color-palette.scss). With most of the themes, most of those values just extend from `--primary`, `--background` and `--background-darker`. But some themes are more complex, and you need to set values individually. 

You can do this from the Theme Configurator → Click "Show All Variables".

It's not really a bug, since some themes just wouldn't be possible using only those three colors.

I _think_ that from there you should be able to set every color. But if there's ever anything else you want to change, you can always add some custom CSS for it (Settings → Custom CSS, or under `appConfig.customCss`). You can also build your own theme, if you want even more customization.

Note that you will loose your progress if you switch themes before you've saved your changes. When you've finished, I recommend also exporting your changes (click "Export Custom Variables"), just to be safe.

**Comment by Entropy-9973** [comment]
> Heya @Entropy-9973
> 
> <img alt="Show all Variables" width="350" src="https://camo.githubusercontent.com/9bc5e80182c224e71673b603f35e9195276c606d1af3a3602821b01eb9946bad/68747470733a2f2f692e6962622e636f2f304a48514a70392f686f772d746f2d73686f772d616c6c2d7661726961626c65732e676966"> [ ](https://camo.githubusercontent.com/9bc5e80182c224e71673b603f35e9195276c606d1af3a3602821b01eb9946bad/68747470733a2f2f692e6962622e636f2f304a48514a70392f686f772d746f2d73686f772d616c6c2d7661726961626c65732e676966) ![Show all Variables](https://camo.githubusercontent.com/9bc5e80182c224e71673b603f35e9195276c606d1af3a3602821b01eb9946bad/68747470733a2f2f692e6962622e636f2f304a48514a70392f686f772d746f2d73686f772d616c6c2d7661726961626c65732e676966) [ ](https://camo.githubusercontent.com/9bc5e80182c224e71673b603f35e9195276c606d1af3a3602821b01eb9946bad/68747470733a2f2f692e6962622e636f2f304a48514a70392f686f772d746f2d73686f772d616c6c2d7661726961626c65732e676966)
> 
> So the way the themes work, is that all the colors are defined as CSS variables, so they can be overridden. Here's the [full list of variables](https://github.com/Lissy93/dashy/blob/master/src/styles/color-palette.scss). With most of the themes, most of those values just extend from `--primary`, `--background` and `--background-darker`. But some themes are more complex, and you need to set values individually.
> 
> You can do this from the Theme Configurator → Click "Show All Variables".
> 
> It's not really a bug, since some themes just wouldn't be possible using only those three colors.
> 
> I _think_ that from there you should be able to set every color. But if there's ever anything else you want to change, you can always add some custom CSS for it (Settings → Custom CSS, or under `appConfig.customCss`). You can also build your own theme, if you want even more customization.
> 
> Note that you will loose your progress if you switch themes before you've saved your changes. When you've finished, I recommend also exporting your changes (click "Export Custom Variables"), just to be safe.


I already tried that, you can try it yourself.
Not a single variable is able to change the navbar background color.
I have tried all of them. That property is simply not accessible through the GUI and this seems to be unique to that theme.

Btw, I just wanna command your project. Very impressive indeed. Best in class

**Comment by Entropy-9973** [comment]
How would you change the color of the navbar in the Material theme ?
It works with Material-dark which should have similar propoerties
