### ISSUE TITLE
Question - Swag and Dashy

### ISSUE THREAD

**Issue by bobcqld53** [Lissy93/dashy#755]
I am using UnRaid to host dashy but cannot get reverse proxy to work via Swag

If I configure Swag -dashy to use authelia - I can log in to authelia Ok but then I get 403 forbidden when re directing to dashy home page.
Dashy docker is configured to use dedicated docker network as per my other reverse proxied containers (All working ok via swag)

**Comment by jthonen** [comment]
Any luck on this?

**Comment by jthonen** [comment]
> I am using UnRaid to host dashy but cannot get reverse proxy to work via Swag
> 
> If I configure Swag -dashy to use authelia - I can log in to authelia Ok but then I get 403 forbidden when re directing to dashy home page. Dashy docker is configured to use dedicated docker network as per my other reverse proxied containers (All working ok via swag)

any luck on this?

**Comment by ehula** [comment]
This was marked closed, but has anyone ever gotten this to work?

**Comment by zachwarner** [comment]
I'm super late to this but thought I'd share since I got it to work. @Lissy93 please let me know if I'm doing anything 🔴 stupid 🔴  here.

The key is to allow `api` access in the proxy conf as a separate `location`, then `allow` specific addresses. For example, [here](https://github.com/linuxserver/reverse-proxy-confs/blob/1ce1eabf54e1e53469894322fb12b1f2b0dbc299/jellyfin.subdomain.conf.sample#L43-L57)'s how SWAG allows `metrics` access to Jellyfin. The whitelisted addresses there are, AFAICT, for same-host and -stack access. 

We adapt this as in the following MRE:

<details>
<summary>glances.subdomain.conf</summary>

```

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name glances.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    
    ...

    location / {
        ...

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app glances;
        set $upstream_port 61208;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location /api {
        allow 192.168.0.0/16;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 127.0.0.0/8;

        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app glances;
        set $upstream_port 61208;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

</details>


<details>
<summary>conf.yml</summary>

```
...

sections:
    ...
    - name: cpu
      widgets:
        - type: gl-current-cpu
          options:
            hostname: https://glances.EXAMPLE.COM
```
</details>
