### ISSUE TITLE
[FEATURE_REQUEST] image widgets with custom header

### ISSUE THREAD

**Issue by maxisam** [Lissy93/dashy#770]
### Is your feature request related to a problem? If so, please describe.

It would be really helpful if we can have a way to add auth header, so this widget can access private api to get image.

This is useful for Grafana, because it generates images with api key in the header

### Describe the solution you'd like

any way to add an api key in the header 

### Priority

Medium (Would be very useful)

**Comment by Lissy93** [comment]
Heya @maxisam 
Should be possible, yup. The source for the image widget is in [`ImageWidget.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/ImageWidget.vue). Would you be up for submitting a PR for this?

**Comment by Lissy93** [comment]
All the functionality for custom headers etc is already there (in the [`WidgetMixin`](https://github.com/Lissy93/dashy/blob/master/src/mixins/WidgetMixin.js)). So it's just a case of tying it together. 

You'd just need to add an option to fetch the image via an XHR request, instead of embedding it directly.

It'd be something like this (totally untested, just vague idea)

```javascript
computed: {
  imagePath() {
    if (!this.options.imagePath) this.error('You must specify an imagePath');
    return this.options.imagePath;
  },
  customHeaders() {
    return this.options.customHeaders || {};
  },
},
methods: {
  fetchData() {
    this.makeRequest(this.imagePath, this.customHeaders).then(this.processData);
  },
  processData(imageResponse) {
    const imageElement = this.$refs.image; // need to add ref to <img> tag first
    const reader = new window.FileReader();
    reader.readAsDataURL(imageResponse); 
    reader.onload = () => imageElement.setAttribute("src", reader.result);
  }
}
```

Or, this could be done without changing any of the code, by using a dynamic widget.

**Comment by maxisam** [comment]
Thanks for quick response!. I don't know which dynamic widget you were referring. https://dashy.to/docs/widgets#dynamic-widgets. I feel like the future API widget might work. 

also I wanna double check with you. I think this is the only way to show Grafana dashboard behind authentication right?

**Comment by Lissy93** [comment]
I'm not sure if this is relevant, maybe their setup is completely different - but I have seen some users with Grafana widgets as (I think) iframes, like [this one](https://github.com/Lissy93/dashy/blob/master/docs/showcase.md#dipans-dash) and [this one](https://github.com/Lissy93/dashy/blob/master/docs/showcase.md#raspberry-pi-docker-dashboard).

But if that doesn't help, I will proceed with trying to add an option to fetch the image via XHR request so that you can pass custom headers.

**Comment by maxisam** [comment]
I think I will try iframe with anonymous. Thanks for helping

**Comment by Lissy93** [comment]
Closing as stale. Let me know in a comment if still relevant.
